# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1179, 557)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setMaximumSize(QtCore.QSize(350, 16777215))
        self.treeWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.treeWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.treeWidget.header().setVisible(False)
        self.gridLayout.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 1, 1, 1)
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setMaximumSize(QtCore.QSize(400, 16777215))
        self.openButton.setAutoExclusive(False)
        self.openButton.setAutoDefault(False)
        self.openButton.setDefault(False)
        self.openButton.setFlat(False)
        self.openButton.setObjectName("openButton")
        self.gridLayout.addWidget(self.openButton, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1179, 21))
        self.menubar.setObjectName("menubar")
        self.file = QtWidgets.QMenu(self.menubar)
        self.file.setObjectName("file")
        self.edit = QtWidgets.QMenu(self.menubar)
        self.edit.setObjectName("edit")
        self.help = QtWidgets.QMenu(self.menubar)
        self.help.setObjectName("help")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.add = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add.setIcon(icon)
        self.add.setObjectName("add")
        self.act_del = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icon/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_del.setIcon(icon1)
        self.act_del.setObjectName("act_del")
        self.saveWord = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icon/word.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveWord.setIcon(icon2)
        self.saveWord.setObjectName("saveWord")
        self.saveExcel = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icon/excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveExcel.setIcon(icon3)
        self.saveExcel.setObjectName("saveExcel")
        self.savePDF = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icon/pdf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.savePDF.setIcon(icon4)
        self.savePDF.setObjectName("savePDF")
        self.print = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icon/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.print.setIcon(icon5)
        self.print.setObjectName("print")
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.about_action = QtWidgets.QAction(MainWindow)
        self.about_action.setObjectName("about_action")
        self.refresh = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/icon/sync.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh.setIcon(icon6)
        self.refresh.setObjectName("refresh")
        self.act_edit = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/icon/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_edit.setIcon(icon7)
        self.act_edit.setObjectName("act_edit")
        self.act_db = QtWidgets.QAction(MainWindow)
        self.act_db.setObjectName("act_db")
        self.file.addAction(self.saveWord)
        self.file.addAction(self.saveExcel)
        self.file.addAction(self.savePDF)
        self.file.addAction(self.print)
        self.file.addSeparator()
        self.file.addAction(self.act_db)
        self.file.addSeparator()
        self.file.addAction(self.exit)
        self.edit.addAction(self.refresh)
        self.edit.addAction(self.act_edit)
        self.edit.addAction(self.add)
        self.edit.addAction(self.act_del)
        self.help.addAction(self.about_action)
        self.menubar.addAction(self.file.menuAction())
        self.menubar.addAction(self.edit.menuAction())
        self.menubar.addAction(self.help.menuAction())
        self.toolBar.addAction(self.print)
        self.toolBar.addAction(self.saveWord)
        self.toolBar.addAction(self.saveExcel)
        self.toolBar.addAction(self.savePDF)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.refresh)
        self.toolBar.addAction(self.act_edit)
        self.toolBar.addAction(self.add)
        self.toolBar.addAction(self.act_del)

        self.retranslateUi(MainWindow)
        self.exit.triggered['bool'].connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "СтройФасад"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Документация"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Входные документы"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Программа строительства на год"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Ведомость объемов СМР на объект"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "План подготовки производства СМР на объект"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "Сводная недельная заявка на доставку бетона и раствора"))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "Почасовая заявка на доставку бетона и раствора"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Справочники"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Справочник материальных ресурсов"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Справочник трудовых ресурсов"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "Выходные документы"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "График производства СМР на объект"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "Ведомость потребности в материалах на объект"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "Ведомость потребности в трудовых ресурсах на объект"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "Суточный график поставки бетона и раствора на объект"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.openButton.setText(_translate("MainWindow", "Открыть выбранный документ"))
        self.file.setTitle(_translate("MainWindow", "Файл"))
        self.edit.setTitle(_translate("MainWindow", "Правка"))
        self.help.setTitle(_translate("MainWindow", "Справка"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.add.setText(_translate("MainWindow", "Добавить"))
        self.act_del.setText(_translate("MainWindow", "Удалить"))
        self.saveWord.setText(_translate("MainWindow", "Сохранить Word"))
        self.saveExcel.setText(_translate("MainWindow", "Сохранить Excel"))
        self.savePDF.setText(_translate("MainWindow", "Сохранить PDF"))
        self.print.setText(_translate("MainWindow", "Печать"))
        self.exit.setText(_translate("MainWindow", "Выход"))
        self.about_action.setText(_translate("MainWindow", "О программе"))
        self.refresh.setText(_translate("MainWindow", "Обновить"))
        self.act_edit.setText(_translate("MainWindow", "Редактировать"))
        self.act_db.setText(_translate("MainWindow", "Подключение к БД"))

import icons_rc
